#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Token {
    EOF,

    Comment(String),
    HashbangComment(String),

    IdentifierName(String),
    PrivateIdentifier(String),

    KeywordAwait,
    KeywordBreak,
    KeywordCase,
    KeywordCatch,
    KeywordClass,
    KeywordConst,
    KeywordContinue,
    KeywordDebugger,
    KeywordDefault,
    KeywordDelete,
    KeywordDo,
    KeywordElse,
    KeywordEnum,
    KeywordExport,
    KeywordExtends,
    KeywordFalse,
    KeywordFinally,
    KeywordFor,
    KeywordFunction,
    KeywordIf,
    KeywordImport,
    KeywordIn,
    KeywordInstanceOf,
    KeywordNew,
    KeywordNull,
    KeywordReturn,
    KeywordSuper,
    KeywordSwitch,
    KeywordThis,
    KeywordThrow,
    KeywordTrue,
    KeywordTry,
    KeywordTypeOf,
    KeywordVar,
    KeywordVoid,
    KeywordWhile,
    KeywordWith,
    KeywordYield,

    DivAssignOp,
    DivOp,
}
